/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package es.edn.helloworld

import spock.lang.Specification

class HelloWorldTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new HelloWorld()

        when:
        def result = lib.sayHello()

        then:
        result == "hello world"
    }
}
