/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package es.edn.helloworld;

/**
 *  A simple class
 */
public class HelloWorld {
    /**
     * Say hello
     * @return the string hello world
     */
    public String sayHello() {
        return "hello world";
    }
}
